const MOVE_PIECE = "MOVE_PIECE";
const SELECT_PIECE = "SELECT_PIECE";
const CLOSE_MODAL = "CLOSE_MODAL";
const OPEN_MODAL = "OPEN_MODAL";
const PROMOTE_PAWN = "PROMOTE_PAWN";

export { MOVE_PIECE, SELECT_PIECE, CLOSE_MODAL, OPEN_MODAL, PROMOTE_PAWN };
