import { PiecePropType } from "../types/types";

export const official: PiecePropType[] = [
  {
    id: 32,
    name: "rook",
    color: "black",
    position: "a1",
    isOut: false,
  },
  {
    id: 31,
    name: "rook",
    color: "black",
    position: "a8",
    isOut: false,
  },
  {
    id: 19,
    name: "king",
    color: "black",
    position: "a5",
    isOut: false,
  },
  {
    id: 20,
    name: "king",
    color: "white",
    position: "h5",
    isOut: false,
  },
  {
    id: 21,
    name: "bishop",
    color: "white",
    position: "h6",
    isOut: false,
  },
  {
    id: 22,
    name: "bishop",
    color: "white",
    position: "h3",
    isOut: false,
  },
  {
    id: 23,
    name: "bishop",
    color: "black",
    position: "a6",
    isOut: false,
  },
  {
    id: 24,
    name: "bishop",
    color: "black",
    position: "a3",
    isOut: false,
  },
  {
    id: 25,
    name: "knight",
    color: "black",
    position: "a2",
    isOut: false,
  },
  {
    id: 26,
    name: "knight",
    color: "black",
    position: "a7",
    isOut: false,
  },
  {
    id: 27,
    name: "knight",
    color: "white",
    position: "h7",
    isOut: false,
  },
  {
    id: 28,
    name: "knight",
    color: "white",
    position: "h2",
    isOut: false,
  },
  {
    id: 29,
    name: "rook",
    color: "white",
    position: "h1",
    isOut: false,
  },
  {
    id: 30,
    name: "rook",
    color: "white",
    position: "h8",
    isOut: false,
  },
  {
    id: 17,
    name: "queen",
    color: "black",
    position: "a4",
    isOut: false,
  },
  {
    id: 18,
    name: "queen",
    color: "white",
    position: "h4",
    isOut: false,
  },
];
